networks:
  server-network:
    driver: bridge

services:
  airquality_app:
    container_name: airquality-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - airquality_db
    networks:
      - server-network
    restart: always
    env_file:
      - .env

  airquality_db:
    container_name: airquality-db-container
    image: postgis/postgis:16-3.5
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/data:/var/lib/postgresql/data
    networks:
      - server-network
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

volumes:
  airquality_db: